---
- name: noaa environment variables
  template:
    src: noaa-v3.conf.j2
    dest: /home/{{ target_user }}/.noaa-v3.conf
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0644

- name: predict directory
  file:
    path: /home/{{ target_user }}/.predict
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: predict config file
  template:
    src: predict.qth.j2
    dest: /home/{{ target_user }}/.predict/predict.qth
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0644

- name: wxtoimg config file
  template:
    src: wxtoimgrc.j2
    dest: /home/{{ target_user }}/.wxtoimgrc
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0644

- name: MeteorDemod config settings.ini file
  template:
    src: settings.ini.j2
    dest: /home/{{ target_user }}/.config/meteordemod/settings.ini
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0644

- name: SatDump config file
  become: yes
  template:
    src: satdump_cfg.json.j2
    dest: /usr/share/satdump/satdump_cfg.json
    owner: root
    group: root
    mode: 0644

- name: wxtoimg license terms acceptance file
  copy:
    src: wxtoimglic
    dest: /home/{{ target_user }}/.wxtoimglic
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0644

- name: log directory for raspberry-noaa-v3 logs
  become: yes
  file:
    path: /var/log/raspberry-noaa-v3
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: logrotate settings for raspberry-noaa-v3 logs
  become: yes
  template:
    src: logrotate-settings.j2
    dest: /etc/logrotate.d/raspberry-noaa-v3
    owner: root
    group: root
    mode: 0644

- name: disable wifi power mgmt script
  become: yes
  copy:
    src: disable-wifi-powermgmt.sh
    dest: /usr/local/sbin/disable-wifi-powermgmt.sh
    owner: root
    group: root
    mode: 0755
  when: disable_wifi_power_mgmt | bool
  register: wifi_powermgmt_script

- name: disable wifi power mgmt service definition
  become: yes
  copy:
    src: disable-wifi-powermgmt.service
    dest: /lib/systemd/system/disable-wifi-powermgmt.service
    owner: root
    group: root
    mode: 0644
  when: disable_wifi_power_mgmt | bool
  register: wifi_powermgmt_service

- name: enable systemd wifi power management disable service
  become: yes
  systemd:
    daemon_reload: yes
    name: disable-wifi-powermgmt.service
    enabled: yes
  when: (wifi_powermgmt_script.changed or wifi_powermgmt_service.changed) and (disable_wifi_power_mgmt|bool)


- name: annotation file (sample for modification)
  copy:
    src: annotation.html.j2_file
    dest: /home/{{ target_user }}/raspberry-noaa-v3/config/annotation/annotation.html.j2
    force: no
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0600

- name: RaspbiNOAA v3 Logo
  copy:
    src: raspberry-noaa-v3-logo.png
    dest: /home/{{ target_user }}/raspberry-noaa-v3/config/annotation/raspberry-noaa-v3-logo.png
    force: yes
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0600

- name: rnv3_utils directory
  file:
    path: /home/{{ target_user }}/.rnv3_utils
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: rnv3_backup_restore script
  copy:
    src: rnv3_backup_restore.sh
    dest: /home/{{ target_user }}/.rnv3_utils
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: rnv3_uninstall script
  copy:
    src: rnv3_uninstall.sh
    dest: /home/{{ target_user }}/.rnv3_utils
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: rnv3_upgrade script
  copy:
    src: rnv3_upgrade.sh
    dest: /home/{{ target_user }}/.rnv3_utils
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: receive_noaa.sh ownership permissions
  file:
    path: /home/{{ target_user }}/raspberry-noaa-v3/scripts/receive_noaa.sh
    state: file
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: receive_meteor.sh ownership permissions
  file:
    path: /home/{{ target_user }}/raspberry-noaa-v3/scripts/receive_meteor.sh
    state: file
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: schedule.sh ownership permissions
  file:
    path: /home/{{ target_user }}/raspberry-noaa-v3/scripts/schedule.sh
    state: file
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755

- name: common.sh ownership permissions
  file:
    path: /home/{{ target_user }}/raspberry-noaa-v3/scripts/common.sh
    state: file
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0755
